### PR TITLE
Time saver

### PR DESCRIPTION
**Pull request by chkboom**

### CODE REVIEW

**Comment by dolphinoracle** [comment]
wait...why do we not enable the swap partitions?

**Comment by chkboom** [comment]
perhaps I should have clarified it better in the message. The swap partition is available and enabled for use by the installed OS and is still in fstab.
I just got rid of the swapon/swapoff that is scattered around regularly in the installer. I originally was concerned about it leaking keys (although I guess since the swap is encrypted, maybe not so much of a problem). I found it also slowed down the installer a bit, particularly when starting the install as well as exiting the installer, it kept getting stuck at the swapoff.

It worked for me even on a 64-bit antiX VM with 192MB RAM allocated to it.

I can add it back in if need be, and if so I would add the swap on and swap off as a separate function that can toggle it on and off - something like enableSwap(bool on).

**Comment by dolphinoracle** [comment]
I had the same thought on the encrypted swap.

It feels weird to me to start with swap enabled (if present) on the live
system, then disable/make new swap/ and not give it back.

there were cases in the old days with antiX where people could not complete
the install with less than 256 MB of ram without swap enabled.  However,
these days I suppose such a machine would be an edge-case (if anything),
given the kernel deprecation of supported hardware.

if anti is OK with the feature removal (swap) then I'm ok with it.

**Comment by AdrianTM** [comment]
If somebody uses toram or something like that that uses a lot of RAM or maybe use dynamic persistency and then they start to run out of RAM and stuff gets swapped off, then when the installer turns swap off the user runs out of RAM at that moment (maybe we need a check of some sort if it's OK to turn off swap), turning the swap back on won't really help much. The installer is pretty lean so if swap off works, the installer should be able to finish successfully most of the times, if the swap off fails then turning it back on later on won't improve things. 

If chkboom tested with 192MB and antiX has a min req. of 256MB I think we are covered.

**Comment by chkboom** [comment]
> I had the same thought on the encrypted swap. It feels weird to me to start with swap enabled (if present) on the live system, then disable/make new swap/ and not give it back.
The worst bit is that you do end up configuring swap beforehand just as a precaution, and a portion of the installer has to go to swap, then as soon as the installer disables the swap, the user's face turns bright red.

> there were cases in the old days with antiX where people could not complete the install with less than 256 MB of ram without swap enabled. However, these days I suppose such a machine would be an edge-case (if anything), given the kernel deprecation of supported hardware. if anti is OK with the feature removal (swap) then I'm ok with it.
I managed to exterminate a bunch of bodge-jobs and refactored things a bit while working on time-saver, so that would probably help with RAM usage too.

**Comment by chkboom** [comment]
> If chkboom tested with 192MB and antiX has a min req. of 256MB I think we are covered.
I actually tried it with 128MB at first and found that the installer wouldn't even start (not even the original installer). Of course these were all done with x86-64 antiX so I can imagine that the 32-bit version would consume slightly less RAM due to things like pointer and integer sizes being half that of a 64-bit OS.

**Pull request merged**
